# Site settings
author: Jackson S. Ramos
title: How To Become A Successful Software Engineer  
header-img: img/home-bg.png
email: jackramos021495@gmail.com
copyright_name: Jackson S. Ramos
description: > # this means to ignore newlines until "baseurl:"
  Modern Day Hieroglyphics
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JackRamos021495

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
